### ISSUE TITLE
CI for python3.8

### ISSUE THREAD

**Issue by pierreglaser** [cloudpipe/cloudpickle#268]
I think we should start setting up CI for python3.8. Probably something like:

```yaml
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.8-dev"  # or maybe "nightly"?
```

@ogrisel ?
