### ISSUE TITLE
Struggling to pickle nested class 

### ISSUE THREAD

**Issue by jakirkham** [cloudpipe/cloudpickle#53]
When setting up an inner class like the one below, `cloudpickle` fails where `dill` would succeed. Based on the rather lengthy traceback, this appears to be due to falling back to Python's standard pickling mechanism.

```
import cloudpickle

class A(object):
    class B(object):
        def __init__(self):
            self.c = 0       
    def __init__(self):
        self.b = A.B()

a = A()
cloudpickle.dumps(a)
```

**Comment by llllllllll** [comment]
This appears to be fixed on master:

```
In [8]: import cloudpickle as cp

In [9]: class C(object):
   ...:     class D(object):
   ...:         def __init__(self):
   ...:             self.attr = 'ayy lmao'
   ...:     def __init__(self):
   ...:         self.attr = self.D()
   ...:         

In [10]: instance = C()

In [11]: cp.dumps(instance)
Out[11]: '\x80\x02ccloudpickle.cloudpickle\n_builtin_type\nq\x00U\x08TypeTypeq\x01\x85q\x02Rq\x03U\x01Cq\x04h\x00U\nObjectTypeq\x05\x85q\x06Rq\x07\x85q\x08}q\t(U\r__slotnames__q\n]q\x0bU\n__module__q\x0cU\x08__main__q\rU\x01Dq\x0eh\x03h\x0eh\x07\x85q\x0f}q\x10(h\x0ch\rU\x07__doc__q\x11NU\x08__init__q\x12ccloudpickle.cloudpickle\n_fill_function\nq\x13(ccloudpickle.cloudpickle\n_make_skel_func\nq\x14h\x00U\x08CodeTypeq\x15\x85q\x16Rq\x17(K\x01K\x01K\x02KCU\rd\x01\x00|\x00\x00_\x00\x00d\x00\x00Sq\x18NU\x08ayy lmaoq\x19\x86q\x1aU\x04attrq\x1b\x85q\x1cU\x04selfq\x1d\x85q\x1eU\x1e<ipython-input-9-79712449f1db>q\x1fh\x12K\x03U\x02\x00\x01q ))tq!Rq"J\xff\xff\xff\xff}q#\x87q$Rq%}q&N}q\'NtRu\x87q(Rq)h\x11Nh\x12h\x13(h\x14h\x17(K\x01K\x01K\x02KCU\x13|\x00\x00j\x00\x00\x83\x00\x00|\x00\x00_\x01\x00d\x00\x00Sq*N\x85q+h\x0eh\x1b\x86q,h\x1d\x85q-U\x1e<ipython-input-9-79712449f1db>q.h\x12K\x05U\x02\x00\x01q/))tq0Rq1J\xff\xff\xff\xffh#\x87q2Rq3}q4N}q5NtRu\x87q6Rq7)\x81q8}q9h\x1bh))\x81q:}q;h\x1bh\x19sbsb.'

In [12]: cp.loads(cp.dumps(instance)).attr.attr
Out[12]: 'ayy lmao'
```

**Comment by jakirkham** [comment]
Just installed from `master` and am still seeing the error above.

Code snippet:

<details>

```python
In [1]: import cloudpickle
   ...: 
   ...: class A(object):
   ...:     class B(object):
   ...:         def __init__(self):
   ...:             self.c = 0       
   ...:     def __init__(self):
   ...:         self.b = A.B()
   ...: 
   ...: a = A()
   ...: cloudpickle.dumps(a)
   ...: 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-5f323b37b3bc> in <module>()
      9 
     10 a = A()
---> 11 cloudpickle.dumps(a)

/zopt/conda2/envs/cpenv/lib/python2.7/site-packages/cloudpickle/cloudpickle.pyc in dumps(obj, protocol)
    827 
    828     cp = CloudPickler(file,protocol)
--> 829     cp.dump(obj)
    830 
    831     return file.getvalue()

/zopt/conda2/envs/cpenv/lib/python2.7/site-packages/cloudpickle/cloudpickle.pyc in dump(self, obj)
    231         self.inject_addons()
    232         try:
--> 233             return Pickler.dump(self, obj)
    234         except RuntimeError as e:
    235             if 'recursion' in e.args[0]:

/zopt/conda2/envs/cpenv/lib/python2.7/pickle.pyc in dump(self, obj)
    222         if self.proto >= 2:
    223             self.write(PROTO + chr(self.proto))
--> 224         self.save(obj)
    225         self.write(STOP)
    226 

/zopt/conda2/envs/cpenv/lib/python2.7/pickle.pyc in save(self, obj)
    329 
    330         # Save the reduce() output and finally memoize the object
--> 331         self.save_reduce(obj=obj, *rv)
    332 
    333     def persistent_id(self, obj):

/zopt/conda2/envs/cpenv/lib/python2.7/site-packages/cloudpickle/cloudpickle.pyc in save_reduce(self, func, args, state, listitems, dictitems, obj)
    692                     "args[0] from __newobj__ args has the wrong class")
    693             args = args[1:]
--> 694             save(cls)
    695 
    696             #Don't pickle transient entries

/zopt/conda2/envs/cpenv/lib/python2.7/pickle.pyc in save(self, obj)
    284         f = self.dispatch.get(t)
    285         if f:
--> 286             f(self, obj) # Call unbound method with explicit self
    287             return
    288 

/zopt/conda2/envs/cpenv/lib/python2.7/site-packages/cloudpickle/cloudpickle.pyc in save_global(self, obj, name, pack)
    546                 d['__new__'] = obj.__new__
    547 
--> 548             self.save_reduce(typ, (obj.__name__, obj.__bases__, d), obj=obj)
    549         else:
    550             raise pickle.PicklingError("Can't pickle %r" % obj)

/zopt/conda2/envs/cpenv/lib/python2.7/site-packages/cloudpickle/cloudpickle.pyc in save_reduce(self, func, args, state, listitems, dictitems, obj)
    711 
    712         if obj is not None:
--> 713             self.memoize(obj)
    714 
    715         # More new special cases (that work with older protocols as

/zopt/conda2/envs/cpenv/lib/python2.7/pickle.pyc in memoize(self, obj)
    242         if self.fast:
    243             return
--> 244         assert id(obj) not in self.memo
    245         memo_len = len(self.memo)
    246         self.write(self.put(memo_len))

AssertionError: 
```

</details>

<br>
Environment:
<br>
<br>

<details>

```yaml
name: cpenv
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::ca-certificates=2017.4.17=0
- conda-forge::certifi=2017.4.17=py27_0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::ncurses=5.9=10
- conda-forge::openssl=1.0.2k=0
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::pip=9.0.1=py27_0
- conda-forge::prompt_toolkit=1.0.14=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::python=2.7.13=1
- conda-forge::readline=6.2=0
- conda-forge::scandir=1.5=py27_1
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::zlib=1.2.11=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - cloudpickle==0.3.0
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.14
```

</details>
